- name: Restart Patrol Agent
  hosts: all
  become: yes
  tasks:
    - name: Restart Patrol Agent
      shell: |
        /opt/bmc/Patrol3/scripts.d ./S50PatrolAgent.sh stop
        /opt/bmc/Patrol3/scripts.d ./S50PatrolAgent.sh start
